<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>SayehBanTools.Framework</RootNamespace>
		<AssemblyName>SayehBanTools.Framework</AssemblyName>

		<!-- مدیریت AssemblyInfo توسط SDK جهت فعال‌سازی Pack -->
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<!-- عدم تولید اتریبیوت‌های تکراری که در فایل AssemblyInfo.cs دستی شما وجود دارند -->
		<GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
		<GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>

		<!-- تنظیمات ساخت پکیج NuGet -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IsPackable>true</IsPackable>
		<PackageId>SayehBanTools.Framework</PackageId>
		<Version>1.0.3</Version>
		<Authors>SayyehBan</Authors>
		<Company>SayyehBan</Company>
		<Title>سورس کمکی فریم ورک سایه بان</Title>
		<Description>مجموعه‌ابزارها و کتابخانه‌های کاربردی برای .NET Framework 4.8</Description>
		<PackageTags>Framework;Tools;SayehBan</PackageTags>
		<Product>SayyehBan.ir</Product>
		<Copyright>SayyehBan.ir</Copyright>
		<PackageIcon>SayyehBan.png</PackageIcon>
		<RepositoryUrl>https://github.com/SayyehBan/SayehBanTools.Framework</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://www.nuget.org/packages/SayehBanTools.Framework</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<!-- تضمین وجود تصویر آیکون هنگام ساخت پکیج -->
		<None Include="..\..\..\..\SayyehBan.png" Link="SayyehBan.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.89" />
		<PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.5.2" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.13" />
		<PackageReference Include="Microsoft.Extensions.Features" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
		<PackageReference Include="Microsoft.Office.Interop.Excel" Version="16.0.18925.20022" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="OllamaSharp" Version="5.4.30" />
		<PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
		<PackageReference Include="RestSharp" Version="114.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="3.3.1" />
		<PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
		<PackageReference Include="System.Reactive.Windows.Forms" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Settings.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Settings.settings</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

</Project>